apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  namespace: unifi
  creationTimestamp: null
  labels:
    app: unifi-controller
  name: unifi-controller-udp
spec:
  ports:
    - name: "stun"
      port: 3478
      protocol: UDP
      targetPort: 3478
    - name: "device-discovery"
      port: 10001
      protocol: UDP
      targetPort: 10001
  selector:
    app: unifi-controller
  type: LoadBalancer
